// defining constants that you need to export

// POSTS COMPONENT (FOR REFERENCE ONLY)
export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'

// BASKET COMPONENT IN USERPAGE AND PRODUCTS CRUD
export const FETCH_BASKET = 'FETCH_BASKET'
export const FETCH_BASKET_BY_ID = 'FETCH_BASKET_BY_ID'
export const POST_BASKET = 'POST_BASKET'
export const PUT_BASKET = 'PUT_BASKET'
export const DELETE_BASKET_ITEM = 'DELETE_BASKET_ITEM'

